document.writeln('<!DOCTYPE html>');
document.writeln('<html>');
document.writeln('<head>');
document.writeln('<meta content="text/javascript;charset=utf-8" />');
document.writeln('	<title>Basic Layout - jQuery EasyUI Demo</title>');
document.writeln('	<link rel="stylesheet" type="text/css" href="../../Content/themes/jquery-easyui-1.3.3/themes/default/easyui.css"/>');
document.writeln('	<link rel="stylesheet" type="text/css" href="../../Content/themes/jquery-easyui-1.3.3/themes/icon.css"/>');
document.writeln('	<link rel="stylesheet" type="text/css" href="../../Content/themes/jquery-easyui-1.3.3/demo/demo.css"/>');
document.writeln('	<script type="text/javascript" src="../../Content/themes/jquery-easyui-1.3.3/jquery.min.js"></script>');
document.writeln('	<script type="text/javascript" src="../../Content/themes/jquery-easyui-1.3.3/jquery.easyui.min.js"></script>');
document.writeln('    </head>');
document.writeln(' <style type="text/css">');
document.writeln('   /*系统提醒按钮图片*/');
document.writeln(' .icon-业务模块');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/业务模块.png\') no-repeat center center;');
document.writeln('}');
document.writeln('');
document.writeln(' .icon-账款');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/账款.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-外发模块');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/外发模块.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-库存');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/库存.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-采购模块');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/采购模块.png\') no-repeat center center;');
document.writeln('}');
document.writeln(' /*基础数据按钮图片*/');
document.writeln('.icon-仓库设置');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/仓库设置.png\') no-repeat center center;');
document.writeln('}');
document.writeln('');
document.writeln(' .icon-产品BOM');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/产品BOM.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-产品类别');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/产品类别.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-产品资料');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/产品资料.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-供应商');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/供应商.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-客户资料');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/客户资料.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-数据导入');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/数据导入.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-银行账户');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/银行账户.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-员工设置');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/员工设置.png\') no-repeat center center;');
document.writeln('}');
document.writeln(' /*采购管理按钮图片*/');
document.writeln(' .icon-采购');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/采购.png\') no-repeat center center;');
document.writeln('}');
document.writeln('/*入库管理按钮图片*/');
document.writeln('.icon-采购入库');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/采购入库.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-采购退货');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/采购退货.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-生产入库');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/生产入库.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-外发入库');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/外发入库.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-外发退料');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/外发退料.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-当前库存');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/当前库存.png\') no-repeat center center;');
document.writeln('}');
document.writeln('/*财务管理管理按钮图片*/');
document.writeln('.icon-财务管理');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/财务管理.png\') no-repeat center center;');
document.writeln('}');
document.writeln('/*报表管理管理按钮图片*/');
document.writeln('.icon-报表');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/报表.png\') no-repeat center center;');
document.writeln('}');
document.writeln('');
document.writeln('/*系统设置管理按钮图片*/');
document.writeln('.icon-系统设置');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统设置.png\') no-repeat center center;');
document.writeln('}');
document.writeln('/*查询、添加、修改按钮图片*/');
document.writeln('.icon-查询');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/查询.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-添加');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/添加.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-修改');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/修改.png\') no-repeat center center;');
document.writeln('}');
document.writeln('');
document.writeln(' </style>');
document.writeln('');
document.writeln('<body>');
document.writeln('<div style="background:url(\'../../Content/图片/主界面顶图片2.png\'); width:1200px;height:20px;">');
document.writeln('   </div>');
document.writeln('@*=上菜单设计######################################################################################*@');
document.writeln('    <a id="btn-edit" href="#" class="easyui-menubutton" data-options="menu:\'#m基础数据\'">基础数据</a>');
document.writeln('  <a href="#" class="easyui-menubutton" data-options="menu:\'#m采购管理\'">采购管理</a>');
document.writeln('  <a href="#" class="easyui-menubutton" data-options="menu:\'#m业务管理\'">业务管理</a>');
document.writeln('  <a href="#" class="easyui-menubutton" data-options="menu:\'#m入库管理\'">入库管理</a>');
document.writeln('  <a href="#" class="easyui-menubutton" data-options="menu:\'#m出库管理\'">出库管理</a>');
document.writeln('   <a href="#" class="easyui-menubutton" data-options="menu:\'#m库存管理\'">库存管理</a>');
document.writeln('  <a href="#" class="easyui-menubutton" data-options="menu:\'#m财务管理\'">财务管理</a>');
document.writeln('  <a href="#" class="easyui-menubutton" data-options="menu:\'#m统计报表\'">统计报表</a>');
document.writeln('   <a href="#" class="easyui-menubutton" data-options="menu:\'#m系统管理\'">系统管理</a>');
document.writeln('   <div id="m基础数据" style="width:150px;">');
document.writeln('		<div>产品类别</div>');
document.writeln('		<div>产品单位</div>');
document.writeln('		<div>产品颜色</div>');
document.writeln('		<div>产品规格</div>');
document.writeln('      <div class="menu-sep"></div>');
document.writeln('		<div>仓库设置</div>');
document.writeln('		<div>产品资料管理</div>');
document.writeln('		<div onclick="$(\'#w产品资料\').window(\'open\')">添加产品</div>');
document.writeln('		<div>产品BOM</div>');
document.writeln('      <div class="menu-sep"></div>');
document.writeln('      <div>供应商类别</div>');
document.writeln('		<div>');
document.writeln('           <span>客户设置</span>');
document.writeln('           <div style="width:150px;">');
document.writeln('');
document.writeln('                <div>客户类型</div>');
document.writeln('		        <div>客户类别</div>');
document.writeln('		        <div>客户等级</div>');
document.writeln('		        <div>客户区域</div>');
document.writeln('                <div>客户阶段</div>');
document.writeln('		        <div>客户行业</div>');
document.writeln('		        <div>客户来源</div>');
document.writeln('		        <div>销售机会</div>');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('		<div>客户资料管理</div>');
document.writeln('		<div>部门设置</div>');
document.writeln('        <div>员工设置</div>');
document.writeln('		<div>员工管理</div>');
document.writeln('      <div class="menu-sep"></div>');
document.writeln('		<div>银行账户管理</div>');
document.writeln('		<div>期初库存建账</div>');
document.writeln('		<div>发票类型设置</div>');
document.writeln('        <div>快递设置</div>');
document.writeln('	</div>');
document.writeln('');
document.writeln('');
document.writeln('');
document.writeln('	<div id="m采购管理" style="width:150px;">');
document.writeln('		<div>供应商报价管理</div>');
document.writeln('		<div>新增供应商报价</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>申购单管理</div>');
document.writeln('		<div>新增申购单</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>采购订单管理</div>');
document.writeln('		<div>新增采购订单</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>外发加工订单管理</div>');
document.writeln('		<div>新增外发加工订单</div>');
document.writeln('	</div>');
document.writeln('    <div id="m业务管理" style="width:150px;">');
document.writeln('		<div>客户跟进管理</div>');
document.writeln('		<div>联系管理</div>');
document.writeln('        <div>销售机会管理</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>客户报价管理</div>');
document.writeln('		<div>新增客户报价</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>客户订单管理</div>');
document.writeln('		<div>新增客户订单</div>');
document.writeln('	    <div class="menu-sep"></div>');
document.writeln('        <div>生产计划管理</div>');
document.writeln('		<div>新增生产计划</div>');
document.writeln('		<div>订单商品需求表</div>');
document.writeln('	</div>');
document.writeln('     <div id="m入库管理" style="width:150px;">');
document.writeln('		<div>采购入库管理</div>');
document.writeln('		<div>新增采购入库</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>采购退货管理</div>');
document.writeln('		<div>新增采购退货</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>生产入库管理</div>');
document.writeln('		<div>新增生产入库</div>');
document.writeln('	    <div class="menu-sep"></div>');
document.writeln('        <div>外发加工入库管理</div>');
document.writeln('		<div>新增外放加工入库</div>');
document.writeln('         <div class="menu-sep"></div>');
document.writeln('        <div>外发加工退料管理</div>');
document.writeln('		<div>新增外发加工退料</div>');
document.writeln('         <div class="menu-sep"></div>');
document.writeln('        <div>生产退料管理</div>');
document.writeln('		<div>新增生产退料</div>');
document.writeln('         <div class="menu-sep"></div>');
document.writeln('        <div>其它入库管理</div>');
document.writeln('		<div>新增其它入库</div>');
document.writeln('	</div>');
document.writeln('    <div id="m出库管理" style="width:150px;">');
document.writeln('		<div>销售出库管理</div>');
document.writeln('		<div>新增销售出库</div>');
document.writeln('        <div>销售排行榜</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>客户退货管理</div>');
document.writeln('		<div>新增客户退货</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>生产领料管理</div>');
document.writeln('		<div>新增生产领料</div>');
document.writeln('	    <div class="menu-sep"></div>');
document.writeln('        <div>外发加工领料管理</div>');
document.writeln('		<div>新增外放加工领料</div>');
document.writeln('         <div class="menu-sep"></div>');
document.writeln('        <div>其他出库管理</div>');
document.writeln('		<div>新增其它出库</div>');
document.writeln('	</div>');
document.writeln('    <div id="m库存管理" style="width:150px;">');
document.writeln('		<div>库存调拨管理</div>');
document.writeln('		<div>新增库存调拨</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>库存盘点管理</div>');
document.writeln('		<div>新增库存盘点</div>');
document.writeln('        <div>产品库存管理</div>');
document.writeln('		<div>产品流向</div>');
document.writeln('        <div>库存调整</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>库存报损管理</div>');
document.writeln('		<div>新增库存报损</div>');
document.writeln('	    <div class="menu-sep"></div>');
document.writeln('        <div>库存报溢管理</div>');
document.writeln('		<div>新增库存报溢</div>');
document.writeln('        <div class="menu-sep"></div>');
document.writeln('        <div>产品拆分管理</div>');
document.writeln('		<div>新增产品拆分</div>');
document.writeln('        <div class="menu-sep"></div>');
document.writeln('        <div>产品组装管理</div>');
document.writeln('		<div>新增产品组装</div>');
document.writeln('	 </div>');
document.writeln('     <div id="m财务管理" style="width:150px;">');
document.writeln('		<div>供应商预付款管理</div>');
document.writeln('		<div>供应商付款管理</div>');
document.writeln('        <div>供应商往来账务</div>');
document.writeln('		<div>供应商对账单</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>客户预收款管理</div>');
document.writeln('		<div>客户收款管理</div>');
document.writeln('        <div>客户往来账务</div>');
document.writeln('		<div>客户对账单</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>支出管理</div>');
document.writeln('		<div>收入管理</div>');
document.writeln('	    <div class="menu-sep"></div>');
document.writeln('        <div>预付款汇总</div>');
document.writeln('		<div>应收款汇总</div>');
document.writeln('        <div class="menu-sep"></div>');
document.writeln('        <div>银行存取款</div>');
document.writeln('		<div>银行转账</div>');
document.writeln('      	<div>银行账务</div>');
document.writeln('	</div>');
document.writeln('     <div id="m统计报表" style="width:150px;">');
document.writeln('		<div>申购报表</div>');
document.writeln('		<div>供应商报价报表</div>');
document.writeln('        <div>采购订单报表</div>');
document.writeln('		<div>采购入库报表</div>');
document.writeln('        <div>采购退货报表</div>');
document.writeln('		<div>外发加工订单报表</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>客户报价报表</div>');
document.writeln('		<div>客户订单报表</div>');
document.writeln('        <div>销售出库报表</div>');
document.writeln('		<div>客户退货报表</div>');
document.writeln('        <div>销售业绩报表</div>');
document.writeln('	    <div class="menu-sep"></div>');
document.writeln('        <div>功能导航</div>');
document.writeln('	</div>');
document.writeln('');
document.writeln('     <div id="m系统管理" style="width:150px;">');
document.writeln('		<div>操作员设置</div>');
document.writeln('		<div>更改密码</div>');
document.writeln('        <div>数据备份</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>打印模板设计</div>');
document.writeln('		<div>系统设置</div>');
document.writeln('        <div>系统初始化</div>');
document.writeln('		<div>系统日志</div>');
document.writeln('		<div class="menu-sep"></div>');
document.writeln('        <div>软件购买</div>');
document.writeln('		<div>在线升级</div>');
document.writeln('        <div>使用帮助</div>');
document.writeln('        <div>官方网站</div>');
document.writeln('        <div>关于本软件</div>');
document.writeln('        <div>锁定系统</div>');
document.writeln('        <div>退出</div>');
document.writeln('	</div>');
document.writeln('    @*=上菜单设计######################################################################################*@');
document.writeln('');
document.writeln('');
document.writeln('      @*=主界面标题*@');
document.writeln('	<div style="background:url(\'http://localhost:2562/Content/图片/主界面标题2.png\'); width:1200px;height:70px;">');
document.writeln('    </div>');
document.writeln('');
document.writeln('    @*=标题图片下面整个操作界面########################################################################*@');
document.writeln('	<div class="easyui-layout" style="width:1200px;height:500px;">');
document.writeln('');
document.writeln('     @*==左边菜单###############*@');
document.writeln('		<div data-options="region:\'west\',split:true" title="隐藏菜单" style="width:150px;">');
document.writeln('');
document.writeln('			<div class="easyui-accordion" data-options="fit:true,border:false,">@*===系统提醒菜单*@');
document.writeln('                <div title="系统提醒" style="padding:10px;">');
document.writeln('');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g1\',plain:true,iconCls:\'icon-采购模块\'"style="width:95%;">采购模块</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g1\',plain:true,iconCls:\'icon-账款\'"style="width:95%;">账款</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g1\',plain:true,iconCls:\'icon-库存\'"style="width:95%;">库存</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g1\',plain:true,iconCls:\'icon-业务模块\'"style="width:95%;">业务模块</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g1\',plain:true,iconCls:\'icon-采购模块\'"style="width:95%;">采购模块</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g1\',plain:true,iconCls:\'icon-外发模块\'"style="width:95%;">外发模块</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g1\',plain:true,iconCls:\'icon-外发模块\'"style="width:95%;">生产模块</a>');
document.writeln('                </div>');
document.writeln('                <div title="基础数据" data-options="selected:true" style="padding:10px;">@*===基础数据*@');
document.writeln('');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-产品类别\'"style="width:95%;">产品类别</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-仓库设置\'"style="width:95%;">仓库设置</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" onclick="$(\'#w产品资料\').window(\'open\')" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-产品资料\'"style="width:95%;">产品资料</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-供应商\'"style="width:95%;">供应商</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-客户资料\'"style="width:95%;">客户资料</a>');
document.writeln('                <a href="#" class="easyui-linkbutton"data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-员工设置\'"style="width:95%;">员工设置</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-银行账户\'"style="width:95%;">银行账户</a>');
document.writeln('                <a href="#" class="easyui-linkbutton"  data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-数据导入\'"style="width:95%;">数据导入</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-产品BOM\'"style="width:95%;">产品BOM</a>');
document.writeln('                </div>');
document.writeln('                <div title="采购管理" style="padding:10px">@*===采购管理*@');
document.writeln('');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">内部申购</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">供应商报价</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">采购订单</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">外发订单</a>');
document.writeln('');
document.writeln('                </div>');
document.writeln('                <div title="业务管理" style="padding:10px">@*===业务管理*@');
document.writeln('');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">客户跟进</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">客户报价</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">客户订单</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">生产计划</a>');
document.writeln('');
document.writeln('                </div>');
document.writeln('                <div title="入库管理" style="padding:10px">@*===入库管理*@');
document.writeln('');
document.writeln('');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-当前库存\'"style="width:95%;">当前库存</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购入库\'"style="width:95%;">采购入库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">外发入库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-生产入库\'"style="width:95%;">生产入库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">其他入库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购退货\'"style="width:95%;">采购退货</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">生产退料</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发退料\'"style="width:95%;">外发退料</a>');
document.writeln('');
document.writeln('                </div>');
document.writeln('                <div title="出库管理" style="padding:10px">@*===出库管理*@');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-当前库存\'"style="width:95%;">当前库存</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购入库\'"style="width:95%;">销售出库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">生产领料</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-生产入库\'"style="width:95%;">外发领料</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">其他出库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购退货\'"style="width:95%;">采购退货</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">销售收款</a>');
document.writeln('                </div>');
document.writeln('                <div title="库存管理" style="padding:10px">@*===库存管理*@');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-当前库存\'"style="width:95%;">当前库存</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购入库\'"style="width:95%;">产品拆分</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">库存报损</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-生产入库\'"style="width:95%;">库存报溢</a>');
document.writeln('');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">库存调拨</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购退货\'"style="width:95%;">产品流向</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发入库\'"style="width:95%;">库存盘点</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-外发退料\'"style="width:95%;">产品组装</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购退货\'"style="width:95%;">库存调整</a>');
document.writeln('');
document.writeln('                </div>');
document.writeln('                <div title="财务管理" style="padding:10px">@*===财务管理*@');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-财务管理\'"style="width:95%;">应收款汇总</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">应付款汇总</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-财务管理\'"style="width:95%;">银行账务</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">收入</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-财务管理\'"style="width:95%;">现金银行</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">支出</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-财务管理\'"style="width:95%;">销售付款</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">存取款</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-财务管理\'"style="width:95%;">采购付款</a>');
document.writeln('');
document.writeln('                </div>');
document.writeln('                <div title="统计报表" style="padding:10px">@*===统计报表*@');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-报表\'"style="width:95%;">采购订单</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">客户订单</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-报表\'"style="width:95%;">采购入库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">销售出库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-报表\'"style="width:95%;">生产领料</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">生产入库</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-报表\'"style="width:95%;">采购退货</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-采购\'"style="width:95%;">销售退货</a>');
document.writeln('');
document.writeln('                </div>');
document.writeln('                <div title="系统管理" style="padding:10px">@*===系统管理*@');
document.writeln('');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-系统设置\'"style="width:95%;">操作员</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-报表\'"style="width:95%;">更改密码</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-系统设置\'"style="width:95%;">数据备份</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-报表\'"style="width:95%;">打印设计</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-系统设置\'"style="width:95%;">系统设置</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-报表\'"style="width:95%;">初始化</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-系统设置\'"style="width:95%;">系统日志</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-报表\'"style="width:95%;">在线升级</a>');
document.writeln('                <a href="#" class="easyui-linkbutton" data-options="toggle:true,group:\'g2\',plain:true,iconCls:\'icon-系统设置\'"style="width:95%;">官方网站</a>');
document.writeln('');
document.writeln('                </div>');
document.writeln('');
document.writeln('			</div>');
document.writeln('		</div>');
document.writeln('        @*==中间数据区域###############*@');
document.writeln('		<div data-options="region:\'center\',title:\'欢迎\',iconCls:\'icon-ok\'">');
document.writeln('        @* 嵌套网页*@');
document.writeln('        <IFRAME src="http://www.baidu.com"style="width:100%;height:100%"scrolling=yes ALLOWTRANSPARENCY="true"></IFRAME>');
document.writeln('');
document.writeln('		</div>');
document.writeln('	</div>');
document.writeln('     @*=标题图片下面整个操作界面########################################################################*@');
document.writeln('');
document.writeln('');
document.writeln('    @*=弹出的产品资料窗体#########################3*@');
document.writeln('    <div id="w产品资料" class="easyui-window" title="产品资料" data-options="modal:true,closed:true,iconCls:\'icon-产品资料\'" style="width:800px;height:500px;padding:10px;">');
document.writeln('		<table>');
document.writeln('            <tr>');
document.writeln('              <td>请输入编号\\拼音码\\规格\\条码\\名称查询：</td>');
document.writeln('               <td><input <input class="submit" style="width:200px"></input></td>');
document.writeln('               <td>');
document.writeln('               <a href="#" class="easyui-linkbutton" data-options="iconCls:\'icon-查询\'">查询</a>');
document.writeln('               <a href="#" class="easyui-linkbutton" data-options="iconCls:\'icon-添加\'">添加</a>');
document.writeln('               <a href="#" class="easyui-linkbutton" data-options="iconCls:\'icon-修改\'">修改</a>');
document.writeln('               <a href="#" class="easyui-linkbutton" data-options="iconCls:\'icon-cancel\'">删除</a>');
document.writeln('               </td>');
document.writeln('');
document.writeln('            </tr>');
document.writeln('        </table>');
document.writeln('         <table>');
document.writeln('               <tr>');
document.writeln('                 <td>');
document.writeln('                 <ul class="easyui-tree"style="width:150px;height:400px">');
document.writeln('');
document.writeln('		        <li>');
document.writeln('');
document.writeln('			        <span>My Documents</span>');
document.writeln('');
document.writeln('			        <ul>');
document.writeln('');
document.writeln('				        <li data-options="state:\'closed\'">');
document.writeln('');
document.writeln('					        <span>Photos</span>');
document.writeln('');
document.writeln('					        <ul>');
document.writeln('');
document.writeln('						        <li>');
document.writeln('');
document.writeln('							        <span>Friend</span>');
document.writeln('');
document.writeln('						        </li>');
document.writeln('');
document.writeln('						        <li>');
document.writeln('');
document.writeln('							        <span>Wife</span>');
document.writeln('');
document.writeln('						        </li>');
document.writeln('');
document.writeln('						        <li>');
document.writeln('');
document.writeln('							        <span>Company</span>');
document.writeln('');
document.writeln('						        </li>');
document.writeln('');
document.writeln('					        </ul>');
document.writeln('');
document.writeln('				        </li>');
document.writeln('');
document.writeln('				        <li>');
document.writeln('');
document.writeln('					        <span>Program Files</span>');
document.writeln('');
document.writeln('					        <ul>');
document.writeln('');
document.writeln('						        <li>Intel</li>');
document.writeln('');
document.writeln('						        <li>Java</li>');
document.writeln('');
document.writeln('						        <li>Microsoft Office</li>');
document.writeln('');
document.writeln('						        <li>Games</li>');
document.writeln('');
document.writeln('					        </ul>');
document.writeln('');
document.writeln('				        </li>');
document.writeln('');
document.writeln('				        <li>index.html</li>');
document.writeln('');
document.writeln('				        <li>about.html</li>');
document.writeln('');
document.writeln('				        <li>welcome.html</li>');
document.writeln('');
document.writeln('			        </ul>');
document.writeln('');
document.writeln('		        </li>');
document.writeln('');
document.writeln('	        </ul>');
document.writeln('');
document.writeln('                 </td>');
document.writeln('');
document.writeln('');
document.writeln('               <td>');
document.writeln('');
document.writeln('');
document.writeln('');
document.writeln('             <table class="easyui-datagrid" title="产品资料" style="width:600px;height:400px"');
document.writeln('');
document.writeln('			        data-options="singleSelect:true,collapsible:true,url:\'../datagrid/datagrid_data1.json\'">');
document.writeln('');
document.writeln('		        <thead>');
document.writeln('');
document.writeln('			        <tr>');
document.writeln('');
document.writeln('				        <th data-options="field:\'itemid\',width:80">Item ID</th>');
document.writeln('');
document.writeln('				        <th data-options="field:\'productid\',width:100">Product</th>');
document.writeln('');
document.writeln('				        <th data-options="field:\'listprice\',width:80,align:\'right\'">List Price</th>');
document.writeln('');
document.writeln('				        <th data-options="field:\'unitcost\',width:80,align:\'right\'">Unit Cost</th>');
document.writeln('');
document.writeln('				        <th data-options="field:\'attr1\',width:250">Attribute</th>');
document.writeln('');
document.writeln('				        <th data-options="field:\'status\',width:60,align:\'center\'">Status</th>');
document.writeln('');
document.writeln('				        <th data-options="field:\'unitcost\',width:80,align:\'right\'">Unit Cost</th>');
document.writeln('');
document.writeln('				        <th data-options="field:\'attr1\',width:250">Attribute</th>');
document.writeln('');
document.writeln('				        <th data-options="field:\'status\',width:60,align:\'center\'">Status</th>');
document.writeln('');
document.writeln('			        </tr>');
document.writeln('');
document.writeln('		        </thead>');
document.writeln('');
document.writeln('');
document.writeln('');
document.writeln('');
document.writeln('');
document.writeln('			        <tr>');
document.writeln('');
document.writeln('				        <td>EST-1</td><td>FI-SW-01</td><td>36.50</td><td>Large</td>');
document.writeln('');
document.writeln('			        </tr>');
document.writeln('');
document.writeln('			        <tr>');
document.writeln('');
document.writeln('				        <td>EST-10</td><td>K9-DL-01</td><td>18.50</td><td>Spotted Adult Female</td>');
document.writeln('');
document.writeln('			        </tr>');
document.writeln('');
document.writeln('			        <tr>');
document.writeln('');
document.writeln('				        <td>EST-11</td><td>RP-SN-01</td><td>28.50</td><td>Venomless</td>');
document.writeln('');
document.writeln('			        </tr>');
document.writeln('');
document.writeln('			        <tr>');
document.writeln('');
document.writeln('				        <td>EST-12</td><td>RP-SN-01</td><td>26.50</td><td>Rattleless</td>');
document.writeln('');
document.writeln('			        </tr>');
document.writeln('');
document.writeln('			        <tr>');
document.writeln('');
document.writeln('				        <td>EST-13</td><td>RP-LI-02</td><td>35.50</td><td>Green Adult</td>');
document.writeln('');
document.writeln('			        </tr>');
document.writeln('');
document.writeln('');
document.writeln('	       </table>');
document.writeln('');
document.writeln('               </td>');
document.writeln('');
document.writeln('               </tr>');
document.writeln('');
document.writeln('                  </table>');
document.writeln('');
document.writeln('	</div>');
document.writeln('    @*=弹出的产品资料窗体#########################3*@');
document.writeln('</body>');
document.writeln('</html>');
