document.writeln('<meta content="text/javascript;charset=utf-8" />');
document.writeln('	<title>Basic Layout - jQuery EasyUI Demo</title>');
document.writeln('	<link rel="stylesheet" type="text/css" href="../../Content/themes/jquery-easyui-1.3.3/themes/default/easyui.css"/>');
document.writeln('	<link rel="stylesheet" type="text/css" href="../../Content/themes/jquery-easyui-1.3.3/themes/icon.css"/>');
document.writeln('	<link rel="stylesheet" type="text/css" href="../../Content/themes/jquery-easyui-1.3.3/demo/demo.css"/>');
document.writeln('	<script type="text/javascript" src="../../Content/themes/jquery-easyui-1.3.3/jquery.min.js"></script>');
document.writeln('	<script type="text/javascript" src="../../Content/themes/jquery-easyui-1.3.3/jquery.easyui.min.js"></script>');
document.writeln('');
document.writeln(' <style type="text/css">');
document.writeln('   /*系统提醒按钮图片*/');
document.writeln(' .icon-业务模块');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/业务模块.png\') no-repeat center center;');
document.writeln('}');
document.writeln('');
document.writeln(' .icon-账款');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/账款.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-外发模块');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/外发模块.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-库存');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/库存.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-采购模块');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统提醒/采购模块.png\') no-repeat center center;');
document.writeln('}');
document.writeln(' /*基础数据按钮图片*/');
document.writeln('.icon-仓库设置');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/仓库设置.png\') no-repeat center center;');
document.writeln('}');
document.writeln('');
document.writeln(' .icon-产品BOM');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/产品BOM.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-产品类别');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/产品类别.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-产品资料');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/产品资料.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-供应商');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/供应商.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-客户资料');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/客户资料.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-数据导入');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/数据导入.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-银行账户');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/银行账户.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-员工设置');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/基础数据/员工设置.png\') no-repeat center center;');
document.writeln('}');
document.writeln(' /*采购管理按钮图片*/');
document.writeln(' .icon-采购');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/采购.png\') no-repeat center center;');
document.writeln('}');
document.writeln('/*入库管理按钮图片*/');
document.writeln('.icon-采购入库');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/采购入库.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-采购退货');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/采购退货.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-生产入库');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/生产入库.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-外发入库');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/外发入库.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-外发退料');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/外发退料.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-当前库存');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/入库管理/当前库存.png\') no-repeat center center;');
document.writeln('}');
document.writeln('/*财务管理管理按钮图片*/');
document.writeln('.icon-财务管理');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/财务管理.png\') no-repeat center center;');
document.writeln('}');
document.writeln('/*报表管理管理按钮图片*/');
document.writeln('.icon-报表');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/报表.png\') no-repeat center center;');
document.writeln('}');
document.writeln('');
document.writeln('/*系统设置管理按钮图片*/');
document.writeln('.icon-系统设置');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/系统设置.png\') no-repeat center center;');
document.writeln('}');
document.writeln('/*查询、添加、修改按钮图片*/');
document.writeln('.icon-查询');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/查询.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-添加');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/添加.png\') no-repeat center center;');
document.writeln('}');
document.writeln('.icon-修改');
document.writeln('{');
document.writeln('    background: url(\'../../Content/图片/修改.png\') no-repeat center center;');
document.writeln('}');
document.writeln('');
document.writeln(' </style>');
